### ISSUE TITLE
Display next random site on thank you page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#109]
When in the "take action" cycle, the "thank you page" should present the user with a further random site to check, so they can quickly cycle through making checks.

The same can apply to people checking a category. The Thank you page can include the category results.

**Comment by dantheta** [comment]
I've merged the thank you text onto the site status, so that once an unblock request has been submitted the user is redirected to a new site status, with thankyou text.  The random URL is drawn from the keyword or category that they just searched for.

This works for keyword and category search.  If they've searched for a site by URL and submitted an unblock request, they'll get the normal thankyou page.

**Comment by dantheta** [comment]
I've added the unblock-cycle functionality to the random site page now.
