### ISSUE TITLE
Missing permalink on report page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#115]
Site blocking report pages lack a shareable permalink to the results

**Comment by dantheta** [comment]
Added permalink to report page.  Is the placement OK?

**Comment by MarcusJT** [comment]
If the "permalink" you've added is the "Share this result" section then it's not fit for purpose as it is because:
(1) it's not actually a hyperlink, just a URL (as text)
(2) it doesn't meet the expectations set by the heading as there's no ability to actually share it other than select, copy & paste it somewhere which will limit its use compared to providing a "copy to clipboard" button which does the work for the user, or perhaps even a standard Share icon which permits copying and sharing the link to all the usual social networks (e.g. as per "Spread the word" section of the site footer)
(3) in addition to the above, the URL of the report page itself should be the permalink, i.e. when you perform a test you should end up on https://stage.blocked.org.uk/site/http://www.domain.com not https://stage.blocked.org.uk/check which will permit saving & sharing the link in other ways (e.g. using browser's bookmark function, native Share features on iOS & Android, etc) which are not usable as the page currently stands.

**Comment by dantheta** [comment]
Hi Marcus,

Thanks for the feedback.  I've added some of the improvements you've suggested, and the permalink is now displayed in a form field with an attached clipboard copy button.

Item (3) Is a good idea.  We're currently using the site results template in two places,: showing static historical results (where the page URL is already matching the permalink's URL)  and for  showing live results from the probe.  I'll get the live results to run under the correct URL soon, and make the /check URL redirect.

**Comment by MarcusJT** [comment]
Great stuff! :)


On 6 Aug 2017 21:23, "Daniel Ramsay" <notifications@github.com> wrote:

Hi Marcus,

Thanks for the feedback. I've added some of the improvements you've
suggested, and the permalink is now displayed in a form field with an
attached clipboard copy button.

Item (3) Is a good idea. We're currently using the site results template in
two places,: showing static historical results (where the page URL is
already matching the permalink's URL) and for showing live results from the
probe. I'll get the live results to run under the correct URL soon, and
make the /check URL redirect.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/openrightsgroup/blocked-org-uk/issues/115#issuecomment-320530209>,
or mute the thread
