### ISSUE TITLE
Improve or change cycling behaviour

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#201]
The "random" element seems to re-represent the same sites very frequently. 

I think from lists and searches it is better to cycle through in list / search rank order.

**Comment by dantheta** [comment]
The list of sites for cycling is currently drawn from the current page of whatever search, list or category the user was looking at before. It should be possible to cycle using strict ordering, but then we might have users racing against each other through the lists. I think shuffling is still a good plan, but we can widen the candidate sites to the entire list, search or category instead of just the current page.

**Comment by JimKillock** [comment]
OK, that makes sense (shuffle but use whole list)
