### ISSUE TITLE
Retest data on saved lists

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#204]
As we will be basing the front page content on saved lists, to make them cleaner material for checking and reporting, we should prioritise any website on the list for retesting and cleaning:

(1) Retest and remove from front page pool anything already unblocked

(2) Retest say fortnightly or weekly

(3) Retest for sites that (a) are http and just hang and (b) redirect; remove these from the front page pool

**Comment by dantheta** [comment]
1 & 2 are done.

**Comment by JimKillock** [comment]
We can leave the redirect pages for reasons mentioned elsewhere (ISPs will unblock them).

Is it possible to remove sites that hang from the pool, and close this ticket?

**Comment by dantheta** [comment]
The daily check will already exclude sites which don't have any blocked results.  I've added a date filter to this check, so that blocked results from inactive lines can't keep a dead site on the frontpage liist.  Redirects will need a bit more thinking about, because that data isn't exposed through the API yet.
