### ISSUE TITLE
Restructure front page

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#255]
Using a 9 x 9 grid:

5 columns background text, 4 columns action block (Is this site incorrectly blocked?)

Place stats after background text in left hand blocks(s)

Keep placement of 'check a site' etc as current

**Comment by dantheta** [comment]
Bootstrap uses a 12 column grid rather than 9, but 7/12 is approximate to 5/9.  I'll put a demo up on stage.blocked.org.uk so that it doesn't block the release of other changes.

**Comment by dantheta** [comment]
Frontpage is in demo on https://stage.blocked.org.uk (same username&password as before).  The comma separators are missing because that server runs an old version of python, they're still there in the real template.

The text alignment in the action box is a tricky decision, I've played about with a bunch of them and can't decide what works best, so let me know what you think.

**Comment by JimKillock** [comment]
Thanks Dan, that's great. I think we can:

(1) Change the text "For example" to "Has this site been blocked in error?"

(2) Change "is blocked for $ISP customers using filters." to "$ISP are blocking this site for customers using filters."

(3) Place buttons under text block and align left with indent of approx 20 px

**Comment by dantheta** [comment]
Updated.  Not sure if I've understood 3 completely, please feel free amend further!

**Comment by JimKillock** [comment]
Looks good to me. Ready to move to live :)
