### ISSUE TITLE
Run .uk and other data tests on BT Strict

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#265]
Can we run .uk and other data tests across the BT Strict line, which looks like it has not run a full pass?

**Comment by JimKillock** [comment]
Noting that this one seems to be running a bit slow, and is on 3,779,163 as of 04 January, 2018 at 13:04

**Comment by JimKillock** [comment]
Then, as of 04 January, 2018 at 13:50 it is 3,779,164 so I guess it is stuck?

**Comment by dantheta** [comment]
It's being throttled back because the Vodafone probe is slower than the others.  Ee was also offline for a bit but is catching up quickly. There's one process that feeds jobs to all the mobile queues, and it pauses when the average target queue length gets too high. Diving everything through and letting the queues hold the data work for smaller lists, but is to much memory with the longer lists.

**Comment by JimKillock** [comment]
Ok, I'm not sure I completely understand but fair enough :) We will need to find ways to separate things off a bit as we go along in order to better utilise the capacity: we can discuss that separately and maybe you can educate me as to the best approach.

**Comment by JimKillock** [comment]
I think we close this but @dantheta I would like to chat with you about how we use the lines and build the test data, we have sat on the .com information for a very long time for instance.
