### ISSUE TITLE
"On hold" reports

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#266]
Some of the "on hold" user reports seem to be stuck in the queue. Can you check why and ensure the queue will check to clear backlogged user reports?

**Comment by dantheta** [comment]
All the pending ones I'm seeing are for talktalk.  It will send those when a test result comes in, and that's dependent on the line.  I'll requeue them when the TT line is installed.

**Comment by JimKillock** [comment]
See: https://www.blocked.org.uk/reported-sites/Vodafone listings for 

http://www.2600.com ; 
http://www.eurogamer.net/articles/sin-and-punishment-2-preview ;
http://www.perkinsdrugs.com 

also https://www.blocked.org.uk/reported-sites/EE/2

http://web.archive.org 

That seems to be it tho.

**Comment by dantheta** [comment]
Interesting. perkins and web.archive.org can't validate their results because the site's robots.txt will not allow the probe to run against them.

The eurogamer one hasn't been released because the submitter hasn't verified their email address.

Others can be pushed through by using force recheck in the admin control panel.  They also get resubmitted daily, providing the site is allowed by robots.txt

**Comment by JimKillock** [comment]
Thanks Dan. Perhaps in the case of probes not being able to check, we could allow a manual admin check and force send?

With users not verifying email, perhaps they should get a reminder, in a pattern: 1 day, 3 days, 7 days, 21 days and discard?

Each reminder can say that the report will be discarded on $date if the email is not verified.

**Comment by JimKillock** [comment]
I'm taking the last suggestion to another ticket for the inbox and closing
