### ISSUE TITLE
Report buttons greyed out: unclear why

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#318]
On this list the report buttons are grey, it is unclear why:

https://www.blocked.org.uk/list/Suicide

**Comment by dantheta** [comment]
The frontpage lists were being periodically rechecked, but the non-frontpage ones (like /list/Suicide) weren't.  The results that had been cached in the frontend had become too old.  I've changed the status refresh so that all lists are updated from the API, but it's still only the frontpage ones that are retested daily.
