### ISSUE TITLE
Treat the https and http entries as the same site

### ISSUE THREAD

**Issue by gwire** [openrightsgroup/blocked-org-uk#322]
Where a site has an entry for `http://www.example.com` and `https://www.example.com` either

1) the frontend should display a link from one to the other

2) both the http and https results should be displayed on the same page

**Comment by dantheta** [comment]
The HTTPS results page now has an information panel directing the user to the HTTP version.  The HTTP version does not link to the HTTPS results page at the moment because the results are rarely more interesting.

Any suggestions for the info panel wording are gratefully received.  It might be a bit too technical in its current form.

**Comment by JimKillock** [comment]
Although the results are less interesting I think a link from http to https may be helpful to navigate backwards and forwards between the two. It also shows we have run the tests and the same blocks should occur. 

Sometimes the https results may be a little bit interesting, for instance a 'dead' site would have differing results where DNS was faking its existence on blocked networks.

**Comment by dantheta** [comment]
Added the HTTPS link on the results page.
