### ISSUE TITLE
Flagging court orders sites that are not matched to injunctions

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#348]
Allow the admin user to access a list of domains with the "URL Whois Expiry	Status" info, plus the ability to add a flag, in the same way as for sites under each court order.

**Comment by JimKillock** [comment]
Checking the admin interface, we have the "Review unmatched" page which we can use for this:

https://www.blocked.org.uk/control/courtorders/review

**Comment by dantheta** [comment]
Added the whois expiry dates.

**Comment by JimKillock** [comment]
Thanks Dan, can you add the ability to flag the court order from the review page.

Currently, we can only flag a domain blocked by URL once it is assigned to a court order. If we don't know which court order it belongs to, we can't flag it as "no court order identified" ;)

(This also relates to the court order index page tickets eg #301 : unassigned domains will need to be in a special group.)

**Comment by dantheta** [comment]
This one's a little bit tricky.  At the moment, the url flag status is held against the association between a URL and a court order, which would allow different flag statuses to be held for different court orders.  That probably isn't going to be a useful distinction (after all, a domain for sale is still exactly that regardless of which/how many court orders the site is subject to).

I can move the url flag status so that it is associated with a URL directly - that way we can easily add these flags to any site in the system.

**Comment by dantheta** [comment]
Another option is to include any unmatched copyright-blocked domain on the reports automatically (the public legal-errors page and the downloadable csv), with the status "no court order identified".  The advantage of this is that there's no additional admin to do when a site is matched - the flag drops away automatically.

**Comment by JimKillock** [comment]
Agree with the latter, that these sites should be on reports. However, I think the data model should not make our observations dependent on its internal status, for instance:

(1) A site might be on a court order page because it was or we suspected (say) torentz-r-us.tw was subject to (say) torrentrus court order

(2) The site is then flagged in that system as "no court order identifiable' because it starts selling Cartier watches rather than supplying torrents.

Plus, over time, the observations and status will change. So perhaps the site stops being blocked and gets removed from the court order pages. We'd want to retain the flagging information and perhaps its previous association with a court order.

**Comment by dantheta** [comment]
The flag buttons are now present on the review page, and show whether a flag exists for a given URL.

I've started to move the flag records so they attach to the URL, instead of the association of the URL and a court order.  This means that the flags will start to exist independantly of the court order(s) that the URL relates to.

**Comment by dantheta** [comment]
I've grouped the URLs together with a list of networks for each (rather than listing each block individually).  Looks pretty clean now.
