### ISSUE TITLE
Bug: Reports are still showing up in site category filter after category has been changed

### ISSUE THREAD

**Issue by alexhaydock** [openrightsgroup/blocked-org-uk#379]
Hi @dantheta,

Just doing some housekeeping work on the "Alcohol" related sites.

I've been switching the category for some sites away from just "Alcohol" and over to "Alcohol related non-alcohol sales"

I've been removing the Alcohol category when I do this so that there's only one category present for each site, but some of the sites are still showing up in the category filter for "Alcohol"

For example:

- https://www.blocked.org.uk/control/ispreports/BT-Strict/http://www.gatesheadbeerfestival.co.uk

Still shows up on this page:

- https://www.blocked.org.uk/control/ispreports?category=Alcohol&state=&network=

**Comment by edjw** [comment]
@dantheta – Can you clarify whether this bug this affecting the count of items in the original category?

**Comment by dantheta** [comment]
The filter selection and reports were ignoring the "enabled" flag on the URL <-> category association table.  Both have been fixed now.  This aggected the paging counts in the report filter setting, and the counts on the ISP report URL category stats.

Merge was also not setting the enabled flag on the target category, so some URLs were added to the target category but in the disabled state.

The URL <-> category table has an enabled state for the non-ORG categories.  If an admin decides to override a categorify categorization, we can't simply delete the association because the next time categorify runs it will add it back again.
