### ISSUE TITLE
Toggle 'View past blocks for this site' and 'Show all results' on block pages

### ISSUE THREAD

**Issue by edjw** [openrightsgroup/blocked-org-uk#393]
On a page like [this one](https://www.blocked.org.uk/site/http://a8c.com), we currently have a link "View past blocks for this site" that reveals all past blocks and a "Show all results" link that reveals all results.

We should allow users to toggle that content rather than a one-way reveal.

When the content is revealed, the links should change to "Hide past results" and "Hide all results". Then, if those links are clicked, the content hides again.

**Comment by dantheta** [comment]
That's live now.

**Comment by edjw** [comment]
(Re-opening this rather than starting a new issue)

@dantheta – the link should say "Hide past results" if the past results are shown when the page is first loaded

<img width="1237" alt="CleanShot 2019-06-07 at 12 21 04@2x" src="https://user-images.githubusercontent.com/6547979/59100732-dbbafe00-891e-11e9-8b25-31a1a2040364.png">

**Comment by dantheta** [comment]
I've improved this a bit - the logic in the show/hide parts of this page may need rethinking.

We were previously hiding the non-blocked results when there were blocked results present, in order to emphasize those.  If there are no blocked results, then we were showing everything.  The past blocks got caught halfway between the two.

I've fixed it in the short term by only displaying the show/hide links when there are blocked results present, preserving the intent of the original show/hide ticket.  

There's probably going to be a revisit of this page, as I've got some template refactoring to do and some tests to write.
