### ISSUE TITLE
Links to Error reporting tools

### ISSUE THREAD

**Issue by JimKillock** [openrightsgroup/blocked-org-uk#73]
Reporting link: Once down to single blocked link there should be three buttons: 
- Check this link (open up link in a web archiver to avoid malware issues) 
- Report this site to {provider name} (opens up form) 
  When a site has been reported, the text and link should change to say
  “Reported to {Provider} on [DD/MM/YYYY]. Report again”
- Tell us about this site (opens up form to ORG - this is to be used if a site is adult/a re-direct or squat)

**Comment by dantheta** [comment]
Basic links present, need to add "Reported to..." behaviour

**Comment by JimKillock** [comment]
At the moment the "report" icon isn't pointing to an actual report form so I haven't had a look. Will there by multiple icons for each provider?

**Comment by dantheta** [comment]
It should be pointing at the form already - it's the loudhailer icon.  
There is a bit of a UX problem at the moment if there aren't enough 
recent results.  The "Re-test this URL" button attempts to get the main 
site to re-test the URL - that flow will be improved.

To test the report form in the short term, find a URL in the category 
browser, submit it for testing on the main blocked.org.uk site, then go 
back to the category browser and click the loudhailer icon.

I've going to change it so that out-of-date results can be retested from 
the reporting form, which will save a lot of clicking & confusion.

Daniel.

**Comment by dantheta** [comment]
I've fixed up the workflow for out-of-date results, so the loudhailer icon will always go to the report form now.  I wanted to add a spinner gif for the re-checking operation, but ModX won't allow .gif files to be uploaded (and it seemed rude to link to the one that ships with the ModX manager)

**Comment by dantheta** [comment]
Added a note for the last report date to the content listing, and also added paging links (next/prev 20).

Ready for review

**Comment by JimKillock** [comment]
This looked good to me - I would add a bit of a gap between tick boxes and text to neaten in up

**Comment by dantheta** [comment]
Added vertical spacing and some padding around the checkboxes.
