### ISSUE TITLE
Remove lines we no longer test

### ISSUE THREAD

**Issue by pamcowburn** [openrightsgroup/blocked-org-uk#79]
Not sure if this appears as an issue elsewhere but can we remove old results that we won't re-test e.g. I noticed http://www.english-heritage.org.uk blocked but it's dated Nov 14 and BT moderate so we won't re-test. Can we just remove these as otherwise people might report them

**Comment by dantheta** [comment]
They are now hidden from the reporting form.  We should update the block totals so that they aren't included in the counts.  At the moment, it's possibile that a site which is only blocked on bt-moderate  would appear on the browser page, but when clicking through to the reporting form, the user would get a "No blocked results found for this URL" message.

**Comment by dantheta** [comment]
Sites which are only blocked on an inactive line are now hidden in the category browser.  The category total updater has been updated, but this takes a while to run.

**Comment by dantheta** [comment]
That should be all done now.
